export const PROPERTIES = [
  { id: '1',  title: 'Skyline Studio',      type: 'apartment',  city: 'tunis',    neighborhood: 'Downtown',          price: 1200, currency: 'TND', period: 'mo', bedrooms: 1, bathrooms: 1, area: 55,  image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600',  featured: true,  description: 'Modern studio in the heart of Tunis downtown.' },
  { id: '2',  title: 'Cozy Villa',           type: 'house',      city: 'tunis',    neighborhood: 'La Marsa',          price: 3500, currency: 'TND', period: 'mo', bedrooms: 4, bathrooms: 2, area: 220, image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600',  featured: true,  description: 'Beautiful villa with garden near the beach.' },
  { id: '3',  title: 'Appartement Moderne',  type: 'apartment',  city: 'sfax',     neighborhood: 'Centre Ville',      price: 900,  currency: 'TND', period: 'mo', bedrooms: 2, bathrooms: 1, area: 85,  image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600',  featured: false, description: 'Appartement bien situé au centre de Sfax.' },
  { id: '4',  title: 'Villa Jasmin',         type: 'house',      city: 'sfax',     neighborhood: 'Sakiet Ezzit',      price: 2800, currency: 'TND', period: 'mo', bedrooms: 3, bathrooms: 2, area: 180, image: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=600',  featured: false, description: 'Villa spacieuse avec parking privé.' },
  { id: '5',  title: 'Studio Sousse Center', type: 'apartment',  city: 'sousse',   neighborhood: 'Medina',            price: 750,  currency: 'TND', period: 'mo', bedrooms: 1, bathrooms: 1, area: 45,  image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600',  featured: false, description: 'Studio moderne proche de la médina de Sousse.' },
  { id: '6',  title: 'Maison Familiale',     type: 'house',      city: 'sousse',   neighborhood: 'Khezama',           price: 2200, currency: 'TND', period: 'mo', bedrooms: 3, bathrooms: 2, area: 150, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',  featured: false, description: 'Maison familiale dans quartier résidentiel calme.' },
  { id: '7',  title: 'Apt Lac Berges',       type: 'apartment',  city: 'tunis',    neighborhood: 'Les Berges du Lac', price: 2100, currency: 'TND', period: 'mo', bedrooms: 3, bathrooms: 2, area: 130, image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600',  featured: true,  description: 'Superbe appartement avec vue lac, standing.' },
  { id: '8',  title: 'Villa Hammamet',       type: 'house',      city: 'hammamet', neighborhood: 'Zone Touristique',  price: 4000, currency: 'TND', period: 'mo', bedrooms: 5, bathrooms: 3, area: 300, image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600',  featured: false, description: 'Villa luxueuse avec piscine à Hammamet.' },
  { id: '9',  title: 'Appartement Nabeul',   type: 'apartment',  city: 'nabeul',   neighborhood: 'Centre',            price: 700,  currency: 'TND', period: 'mo', bedrooms: 2, bathrooms: 1, area: 80,  image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600',  featured: false, description: 'Appartement calme et lumineux à Nabeul.' },
  { id: '10', title: 'Duplex Monastir',      type: 'apartment',  city: 'monastir', neighborhood: 'Skanes',            price: 1500, currency: 'TND', period: 'mo', bedrooms: 3, bathrooms: 2, area: 120, image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600',  featured: false, description: 'Duplex moderne vue mer à Skanes Monastir.' },
  { id: '11', title: 'Chambre Meublée',      type: 'room',       city: 'tunis',    neighborhood: 'Bab Souika',        price: 350,  currency: 'TND', period: 'mo', bedrooms: 1, bathrooms: 1, area: 18,  image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600',  featured: false, description: 'Chambre meublée avec accès cuisine partagée.' },
  { id: '12', title: 'Room Near University', type: 'room',       city: 'sfax',     neighborhood: 'Route Menzel',      price: 280,  currency: 'TND', period: 'mo', bedrooms: 1, bathrooms: 1, area: 15,  image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600',  featured: false, description: 'Chambre proche de la faculté des sciences de Sfax.' },
  { id: '13', title: 'Chambre Sousse',       type: 'room',       city: 'sousse',   neighborhood: 'Sahloul',           price: 300,  currency: 'TND', period: 'mo', bedrooms: 1, bathrooms: 1, area: 16,  image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600',  featured: false, description: 'Chambre dans appartement partagé, quartier calme.' },
  { id: '14', title: 'Bureau Moderne',       type: 'commercial', city: 'tunis',    neighborhood: 'Les Berges du Lac', price: 2500, currency: 'TND', period: 'mo', bedrooms: 0, bathrooms: 1, area: 80,  image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600',  featured: false, description: 'Bureau moderne open space dans immeuble professionnel.' },
  { id: '15', title: 'Local Commercial',     type: 'commercial', city: 'sfax',     neighborhood: 'Centre Ville',      price: 1800, currency: 'TND', period: 'mo', bedrooms: 0, bathrooms: 1, area: 60,  image: 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=600',  featured: false, description: 'Local commercial en rez-de-chaussée, grande vitrine.' },
  { id: '16', title: 'Espace de Coworking',  type: 'commercial', city: 'tunis',    neighborhood: 'El Menzah',         price: 600,  currency: 'TND', period: 'mo', bedrooms: 0, bathrooms: 1, area: 25,  image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=600',  featured: false, description: 'Poste de travail dans espace coworking moderne.' },
];

export const CITIES = ['Tunis', 'Sfax', 'Sousse', 'Hammamet', 'Nabeul', 'Monastir', 'Bizerte', 'Kairouan', 'Gabès', 'Ariana'];
