/**
 * Workers data for each service category.
 * Keys must match the `title` values in ServicesScreen SERVICES array.
 */
export const workers = {
  Plumbing: [
    {
      id: 'pl-1',
      name: 'Mehdi Ben Ali',
      experience: '8 ans',
      rating: 4.8,
      reviews: 132,
      pricePerHour: 35,
      phone: '21 234 567',
      specialties: ['Fuite d\'eau', 'Installation sanitaire', 'Débouchage'],
    },
    {
      id: 'pl-2',
      name: 'Yassine Mbarki',
      experience: '5 ans',
      rating: 4.5,
      reviews: 87,
      pricePerHour: 28,
      phone: '22 345 678',
      specialties: ['Chauffe-eau', 'Robinetterie', 'Tuyauterie'],
    },
    {
      id: 'pl-3',
      name: 'Sami Trabelsi',
      experience: '12 ans',
      rating: 4.9,
      reviews: 214,
      pricePerHour: 45,
      phone: '23 456 789',
      specialties: ['Urgence 24/7', 'Rénovation salle de bain', 'Pompe'],
    },
    {
      id: 'pl-4',
      name: 'Farouk Jlassi',
      experience: '3 ans',
      rating: 4.2,
      reviews: 41,
      pricePerHour: 22,
      phone: '24 567 890',
      specialties: ['Débouchage', 'Fuite d\'eau'],
    },
  ],

  Electrician: [
    {
      id: 'el-1',
      name: 'Anis Souissi',
      experience: '10 ans',
      rating: 4.9,
      reviews: 198,
      pricePerHour: 40,
      phone: '25 678 901',
      specialties: ['Tableau électrique', 'Installation', 'Dépannage'],
    },
    {
      id: 'el-2',
      name: 'Rami Khlifi',
      experience: '6 ans',
      rating: 4.6,
      reviews: 103,
      pricePerHour: 32,
      phone: '26 789 012',
      specialties: ['Climatisation', 'Câblage', 'Prises'],
    },
    {
      id: 'el-3',
      name: 'Bilel Ghali',
      experience: '4 ans',
      rating: 4.3,
      reviews: 59,
      pricePerHour: 25,
      phone: '27 890 123',
      specialties: ['Éclairage LED', 'Interphones', 'Sécurité'],
    },
    {
      id: 'el-4',
      name: 'Tarek Hammami',
      experience: '15 ans',
      rating: 5.0,
      reviews: 312,
      pricePerHour: 55,
      phone: '28 901 234',
      specialties: ['Urgence 24/7', 'Rénovation complète', 'Normes NFC 15-100'],
    },
  ],

  Cleaning: [
    {
      id: 'cl-1',
      name: 'Nadia Baccouche',
      experience: '7 ans',
      rating: 4.8,
      reviews: 267,
      pricePerHour: 18,
      phone: '29 012 345',
      specialties: ['Ménage complet', 'Après déménagement', 'Vitres'],
    },
    {
      id: 'cl-2',
      name: 'Rim Chaabane',
      experience: '4 ans',
      rating: 4.7,
      reviews: 154,
      pricePerHour: 15,
      phone: '20 123 456',
      specialties: ['Nettoyage bureaux', 'Tapis & moquette', 'Désinfection'],
    },
    {
      id: 'cl-3',
      name: 'Salma Ayari',
      experience: '9 ans',
      rating: 4.9,
      reviews: 389,
      pricePerHour: 22,
      phone: '21 234 001',
      specialties: ['Nettoyage en profondeur', 'Cuisine', 'Salle de bain'],
    },
    {
      id: 'cl-4',
      name: 'Amira Belhaj',
      experience: '2 ans',
      rating: 4.4,
      reviews: 38,
      pricePerHour: 12,
      phone: '22 345 002',
      specialties: ['Ménage régulier', 'Repassage'],
    },
    {
      id: 'cl-5',
      name: 'Fatma Oueslati',
      experience: '6 ans',
      rating: 4.6,
      reviews: 112,
      pricePerHour: 16,
      phone: '23 456 003',
      specialties: ['Entreprise', 'Résidentiel', 'Évènementiel'],
    },
  ],

  Moving: [
    {
      id: 'mv-1',
      name: 'Slim Bouzid',
      experience: '11 ans',
      rating: 4.7,
      reviews: 176,
      pricePerHour: 50,
      phone: '24 567 004',
      specialties: ['Déménagement complet', 'Emballage', 'Stockage'],
    },
    {
      id: 'mv-2',
      name: 'Hassen Labidi',
      experience: '5 ans',
      rating: 4.5,
      reviews: 91,
      pricePerHour: 40,
      phone: '25 678 005',
      specialties: ['Meubles lourds', 'Piano', 'Montage/démontage'],
    },
    {
      id: 'mv-3',
      name: 'Karim Farhat',
      experience: '8 ans',
      rating: 4.6,
      reviews: 138,
      pricePerHour: 45,
      phone: '26 789 006',
      specialties: ['Petits déménagements', 'Objets fragiles'],
    },
  ],

  Painting: [
    {
      id: 'pa-1',
      name: 'Mourad Dridi',
      experience: '14 ans',
      rating: 4.8,
      reviews: 203,
      pricePerHour: 30,
      phone: '27 890 007',
      specialties: ['Peinture intérieure', 'Enduit', 'Décoration'],
    },
    {
      id: 'pa-2',
      name: 'Lotfi Riahi',
      experience: '6 ans',
      rating: 4.5,
      reviews: 78,
      pricePerHour: 25,
      phone: '28 901 008',
      specialties: ['Peinture extérieure', 'Ravalement', 'Anti-humidité'],
    },
    {
      id: 'pa-3',
      name: 'Walid Nasri',
      experience: '3 ans',
      rating: 4.3,
      reviews: 34,
      pricePerHour: 20,
      phone: '29 012 009',
      specialties: ['Peinture décorative', 'Effets matière'],
    },
  ],

  Carpentry: [
    {
      id: 'ca-1',
      name: 'Maher Karray',
      experience: '16 ans',
      rating: 4.9,
      reviews: 251,
      pricePerHour: 45,
      phone: '20 123 010',
      specialties: ['Cuisine sur mesure', 'Placards', 'Menuiserie générale'],
    },
    {
      id: 'ca-2',
      name: 'Fathi Zouari',
      experience: '9 ans',
      rating: 4.7,
      reviews: 117,
      pricePerHour: 38,
      phone: '21 234 011',
      specialties: ['Portes & fenêtres', 'Parquet', 'Escaliers'],
    },
    {
      id: 'ca-3',
      name: 'Khaled Missaoui',
      experience: '5 ans',
      rating: 4.4,
      reviews: 62,
      pricePerHour: 28,
      phone: '22 345 012',
      specialties: ['Réparation meubles', 'Pose de parquet', 'Petits travaux'],
    },
  ],
};
